apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: trieve-keycloak
spec:
  instances: 1
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      memory: 2Gi
  db:
    vendor: postgres
    host: trieve-keycloak-db-cluster-rw
    usernameSecret:
      name: trieve-keycloak-db-cluster-app
      key: username
    passwordSecret:
      name: trieve-keycloak-db-cluster-app
      key: password
  http:
    httpEnabled: true
  ingress:
    enabled: false
  hostname:
    strict: false
    hostname: http://trieve-keycloak-service:8080
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
